name: technical-internship
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - "numpy>=1.24,<2"
      - "ruff>=0.9,<1"
      - "ipykernel>=6.29,<7"
      - "nbclient>=0.10,<1"
      - "nbconvert>=7.16,<8"
      - "nbformat>=5.10,<6"
      - "pandas>=2,<3"
      - "scikit-learn>=1.3,<2"
      - "torch>=2.2,<2.3"
